### ISSUE TITLE
[Android] Don't require google-services.json for debug builds

### ISSUE THREAD

**Issue by rtsisyk** [omapsapp/omapsapp#189]
This configuration file is needed for Crashlytics. It makes no sense to have Crashlytics enabled for debug builds.

**Comment by rtsisyk** [comment]
Done

**Comment by smartyw** [comment]
This still seems to be a problem. I forked on 15th May 2021 and attempts to build with ./gradle --info clean runWebDebug fails with this output at the end:

```
> Task :processWebDebugGoogleServices FAILED
Task :processWebDebugGoogleServices in android Starting
Caching disabled for task ':processWebDebugGoogleServices' because:
  Caching has not been enabled for the task
Task ':processWebDebugGoogleServices' is not up-to-date because:
  Task has failed previously.
Parsing json file: /Users/martin/AndroidStudioProjects/organicmaps/android/google-services.json
Task :processWebDebugGoogleServices in android Finished
:processWebDebugGoogleServices (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.005 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processWebDebugGoogleServices'.
> No matching client found for package name 'app.organicmaps.debug'

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
```

**Comment by biodranik** [comment]
It was fixed yesterday in the master.

**Comment by smartyw** [comment]
Hi @biodranik , I'm still seeing the same problem. My fork is "even with organicmaps:master" as of five minutes ago and my local repo is up to date. Could I be doing something incorrectly?

```
> Task :processWebDebugGoogleServices FAILED
Task :processWebDebugGoogleServices in android Starting
Caching disabled for task ':processWebDebugGoogleServices' because:
  Caching has not been enabled for the task
Task ':processWebDebugGoogleServices' is not up-to-date because:
  Task has failed previously.
Parsing json file: /Users/martin/AndroidStudioProjects/organicmaps/android/google-services.json
Task :processWebDebugGoogleServices in android Finished
:processWebDebugGoogleServices (Thread[Execution worker for ':',5,main]) completed. Took 0.004 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processWebDebugGoogleServices'.
> No matching client found for package name 'app.organicmaps.debug'
```

```
martin@Raticate android % git log -n 5 > ~/tmp/git_history.txt 
martin@Raticate android % cat ~/tmp/git_history.txt          
commit b22cb03e2d438fce7b6a7e7f771578a5ae67f323
Author: Francesco Gazzetta <fgaz@fgaz.me>
Date:   Sun May 16 16:22:08 2021 +0200

    Remove executable bit from data files
    
    It could cause problems in packaging: some distributions do not allow
    executable files in data directories.
    
    Signed-off-by: Francesco Gazzetta <fgaz@fgaz.me>

commit e1d84ec1cf3beac12925bf4332b3e236872d0cca
Author: Francesco Gazzetta <fgaz@fgaz.me>
Date:   Sun May 16 17:44:10 2021 +0200

    Update .desktop file and desktop logo
    
    The logo was copied from the xhdpi android one, that has the same shape
    and size.
    
    The deskop file assumes that the icon is installed as "organicmaps.png"
    
    Signed-off-by: Francesco Gazzetta <fgaz@fgaz.me>

commit 0a134c430ce3b8eb43e950db4ea0bfba3a59bcd5
Author: Roman Tsisyk <roman@tsisyk.com>
Date:   Sun May 16 11:58:50 2021 +0300

    [android]: Merge two StorageUtils classes into one
    
    No semantic changes intended. This patch is pure refactoring.
    
    Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

commit 86277837e5d48183c6a14b2291c9b0874e8408a6
Author: Roman Tsisyk <roman@tsisyk.com>
Date:   Sun May 16 10:56:41 2021 +0300

    [android] Remove overengineering from BookmarkCategoryAdapter
    
    Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

commit c456bb6953656f067cc57bf2653a1528c27c3981
Author: Alexander Borsuk <me@alex.bio>
Date:   Sun May 16 00:46:59 2021 +0200

    [android] Updated gitignore
    
    Network policy is created by ./configure.sh script
    
    Signed-off-by: Alexander Borsuk <me@alex.bio>
```

**Comment by biodranik** [comment]
Sid you run ./configure.sh ?

**Comment by smartyw** [comment]
I did.... but not since I resynced my fork.... I guess that was necessary because I just tried again and... over an hour later.... it worked (except I had no device plugged in at the time). Looking good. Thanks for the tip.
